update requirements.txt with flake8, add .flake8 config and add linti…
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #167
Opened 2017-10-20 13:45 UTC by mathagician

2017-10-20 16:29 UTC, tapasweni-pathak commented on oshc/main/templates/contest_submission.html
> +      <h1 class="display-3">Thank you!</h1>
👋 You are trying to resolve two issues in this pull request. :)

2017-10-20 16:34 UTC, tapaswenipathak requested changes
Thanks for the work! I have added few comments after that we are good to go!

2017-10-20 16:34 UTC, tapasweni-pathak commented on .travis.yml
> +  - flake8 --ignore E226,E302,E41,F401,E402 .
We'll also check these. Can you please remove the ignored ones.

2017-10-20 16:34 UTC, tapasweni-pathak commented on requirements.txt
> +flake8==3.4.1
We can just have flake8.

2017-10-22 07:34 UTC, mathagician commented
ok I shall give an updated request one for each issue.

2017-10-22 07:45 UTC, tapasweni-pathak commented
One way is to push changes to this pull request, then squash them later. Other very easy and not so good way is to close this pull request and create a new one with changes and suggestions accommodated. Let us know if you face issues while trying out these.

2017-10-22 11:57 UTC, mathagician commented
I have given a new PR at https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/178 

Please see and review.

2017-10-23 14:14 UTC, tapaswenipathak reviewed
Closing this one as you have submitted  #178.

2017-10-23 14:14 UTC, closed without merging