Create dev.txt
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #171
Opened 2017-10-20 22:59 UTC by kaysiz

**Checklist**

- [ ] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: fixes #
https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/issues/165
Brief description of what this PR does.
added the dev.txt file, empty for now
Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber"
First Steps for Issues #165 
**Why do we need this PR?**:
Other users can update the file
If relevant, please include a screenshot.

**Demo (optional)**:

Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.

**Testing instructions:**

If there is any work still left to do, please add it here.

**TODOs (if any)**:

**A picture of a cute animal (not mandatory but encouraged)**:

2017-10-21 01:30 UTC, tapaswenipathak requested changes

2017-10-21 01:30 UTC, tapasweni-pathak commented on dev.txt
> +Django==1.11.6
We need not repeat this in dev.txt. You can start with ```-r prod.txt``` in dev.txt. Have all but ```coverage``` in prod.txt. Just have ```coverage``` here. Also merge #171 and #172. I will close #172. Then we are good to go with this!

2017-11-11 11:01 UTC, jarifibrahim commented
@kaysiz Ping!! Are you still working on this?

2017-11-12 20:20 UTC, kaysiz commented
@jarifibrahim ping!! No i am not.

2017-11-18 13:15 UTC, closed without merging