Anna predev
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #173
Opened 2017-10-21 01:52 UTC by amakarudze

**Checklist**

- [ ] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: fixes #

Brief description of what this PR does.
Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber"

**Why do we need this PR?**:

If relevant, please include a screenshot.

**Demo (optional)**:

Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.

**Testing instructions:**
- Add SECRET_KEY to environment settings. 
- To test for different settings use "python manage.py runserver --settings=oshc.settings.filename" where filename can be dev, predev or production.

If there is any work still left to do, please add it here.

**TODOs (if any)**:
- I updated .gitignore with the .ve/ in the virtualenv section because that it what I had named my virtualenv and can be removed. 
- You would need to add SECRET_KEY to environment settings and there is need to add the instructions to the README.md of the project for contributors.

**A picture of a cute animal (not mandatory but encouraged)**:

2017-10-21 02:03 UTC, amakarudze commented
os import is covered by "from .base import *".

2017-10-21 20:52 UTC, tapaswenipathak requested changes

2017-10-21 20:52 UTC, tapasweni-pathak commented on oshc/oshc/settings/base.py
> +SECRET_KEY = get_env_variable('SECRET_KEY')
If you are removing the secret key, then you also need to enable it in for Travis. In ```.travis.yml```, you need to export like 
```
before_script:
  - export SECRET_KEY=<key>
```

Currently Travis is failing. You can keep the key as ```foobaroshc```.

2017-11-18 13:22 UTC, tapasweni-pathak commented
:wave: amakarudze, working on this?

2017-11-18 20:25 UTC, amakarudze commented
Yes, I thought I had submitted a pull request for it some few weeks back. I
will check again.

Thanks.

On 18 November 2017 at 15:22, Tapasweni Pathak <notifications@github.com>
wrote:

> 👋 amakarudze, working on this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/173#issuecomment-345442030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AM9qxYKqEwpOMdpuODvxvrE7H5jjTOMRks5s3toigaJpZM4QBZMH>
> .
>

2017-12-15 20:11 UTC, closed without merging