Use crispy forms in contest view
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #181
Opened 2017-10-23 16:41 UTC by AlexPnt

**Checklist**

- [x] My branch is up-to-date with the upstream `develop` branch.
- [x] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: 

Use crispy forms in contest view.
Fixes #141

2017-10-25 06:54 UTC, vaibhavsingh97 requested changes
LGTM!! Nice work 👍 
What I think is that intead of giving error of `wrong date` we should give the example with the error to help the user.  Btw I will prefer datepicker over writing date. Can You please change it to to date picker

2017-10-25 06:54 UTC, vaibhavsingh97 commented on oshc/main/templates/contest_edit.html
> +        <div class="form-group">#}
Remove extra `}`

2017-10-25 10:37 UTC, AlexPnt commented
Date pickers added !

2017-10-25 18:17 UTC, vaibhavsingh97 commented
@AlexPnt I am not able to add date as it's disabled everything after current date
![image](https://user-images.githubusercontent.com/8705386/32015425-99eb093c-b9b0-11e7-885e-7290cfda4641.png)

2017-10-28 02:18 UTC, tapaswenipathak approved these changes
Wohoo! 🚀 Thanks for the work and review! Had to squash, so merged with commit 7aa856a4255fceeb26a69c9c6b0c685848105cc6.

2017-10-28 02:20 UTC, closed without merging