Disabled users from entering the same email id
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #61
Opened 2017-07-07 13:08 UTC by mish24

Fix for issue #52. 
However I'm still not sure how to notify the users regarding the issue. Shall it be done by form or templates? As of now this PR doesn't allow it and keeps the user on the page.

2017-07-07 13:09 UTC, mish24 commented
I'll create a separate PR if required. This addresses two small issues in one.

2017-07-07 16:21 UTC, amarlearning requested changes
You didn't add the error message. some kind of error message should be shown to the user.

2017-07-07 16:21 UTC, amarlearning commented on oshc/oshc/settings.py
> +LOGOUT_REDIRECT_URL = 'home'
Extraneous change.

2017-07-08 08:09 UTC, mish24 commented on oshc/oshc/settings.py
> +LOGOUT_REDIRECT_URL = 'home'
Okay, I'll send a different PR for this issue!

2017-07-14 17:18 UTC, tapasweni-pathak commented
@mish24 Are you still working on this pull request?

2017-07-15 20:09 UTC, amarlearning commented
@mish24 Closing due to inactivity (we try to keep the PR list clean). Feel free to reopen when you have new changes to push :)

2017-07-15 20:09 UTC, closed without merging