Added ADMINS to settings.py
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #64
Opened 2017-07-08 06:10 UTC by Utsal20

Issue #49 completed. Admins are added to settings.py

2017-07-08 08:47 UTC, nikhita approved these changes

2017-07-08 08:48 UTC, nikhita commented
@Utsal20 Thanks! I'll let @jarifibrahim take a look at it too before merging it. :+1:

2017-07-08 08:57 UTC, tapasweni-pathak commented
@Utsal20 Can you please add @amarlearning (amar.om1994@gmail.com) too?

2017-07-08 08:58 UTC, nikhita commented
@Utsal20 I modified the PR description to read `Fixes #49` instead of `Issue #49`. When we write like this, it automatically closes the issue once this PR is merged! :smile: 

More details here: https://github.com/blog/1506-closing-issues-via-pull-requests, https://help.github.com/articles/closing-issues-via-commit-messages/.

2017-07-08 10:31 UTC, jarifibrahim approved these changes
LGTM. I'll merge after you add Amar Prakash Pandey (amar.om1994@gmail.com) to Admins.

2017-07-08 11:47 UTC, amarlearning requested changes

2017-07-08 11:47 UTC, amarlearning commented on oshc/oshc/settings.py
> +
Extraneous change. Having two consecutive new lines is not a good practice. [[more read](http://pep8.org/#blank-lines)]

I think we should split the list something like this for better readability. [[more read](http://pep8.org/#maximum-line-length)]
```python
ADMINS = [
     ('Tapasweni Pathak','tapaswenipathak@gmail.com'),
     ('Nikhita Raghunath','nikitaraghunath@gmail.com'),
     ('Ibrahim Jarif','jarifibrahim@gmail.com')
]
```

2017-07-09 01:45 UTC, Utsal20 commented on oshc/oshc/settings.py
> +
Thank you for your suggestions!
I just did:
git add oshc/oshc/settings.py
git push -u origin master
Will this be enough? Or is there something I am missing?

2017-07-09 09:23 UTC, tapasweni-pathak commented
Can I please merge this one @amarlearning? or you would suggest @Utsal20 to squash commits? 😄

I see it's @Utsal20's first pull request. ✨

2017-07-09 09:30 UTC, tapasweni-pathak commented
I am merging this sorry, can't wait. Congrats for your first pull request @Utsal20! 🎆 

But @Utsal20 there is something as [squashing commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) in which if you have fixed your previous commit or you have many related commits separate you can squash them as one. I am sure these two would have suggested you to do this before merging, so surely have a read, for all next pull requests you have to. :)

2017-07-09 09:31 UTC, tapasweni-pathak commented
I am merging this sorry, can't wait. Congrats for your first pull request @Utsal20! 🎆 

But @Utsal20 there is something as [squashing commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) in which if you have fixed your previous commit or you have many related commits separate you can squash them as one. I am sure these two would have suggested you to do this before merging, so surely have a read, for all next pull requests you have to. :)

2017-07-09 09:31 UTC, merged

2017-07-09 18:38 UTC, Utsal20 commented
Thank you so much for your support guys! Will do the reading.