User can login through either email or username
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #67
Opened 2017-07-08 09:48 UTC by vaibhavsingh97

fixes #54

2017-07-08 16:08 UTC, jarifibrahim requested changes

2017-07-08 16:08 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +class EmailBackend(object):
`EmailLoginBackend` would make more sense than `EmailBackend`

2017-07-08 16:08 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +class EmailBackend(object):
Please add a comment below the class name stating the use of this backend.

2017-07-08 16:08 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +        except:
You should never use a bare except clause. Read [this](https://stackoverflow.com/questions/18982610/difference-between-except-and-except-exception-as-e-in-python) for more info.

Both the except clause perform the same action, you should consider using a single except clause instead of two.
A single `except user_cls.DoesNotExists` should be sufficient.

2017-07-08 16:08 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +    def authenticate(self, username=None, password=None):
The `authenticate` method should `return None` when the authentication credentials are invalid. Your `authenticate` function returns None implicitly. The intention of your code is much clearer with an explicit `return None`. :)

2017-07-08 17:09 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +    def authenticate(self, username=None, password=None):
@vaibhavsingh97 Ping! You missed this change request.

2017-07-08 17:19 UTC, vaibhavsingh97 commented
@jarifibrahim Please review again :smile:

2017-07-08 17:56 UTC, jarifibrahim requested changes
@vaibhavsingh97 Please squash your commits. Too many commits for a single issue.

2017-07-08 17:56 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +
Add a `return None` on line 17.

2017-07-08 17:56 UTC, jarifibrahim commented on oshc/main/templates/session.html
> +
Extraneous change. Please do not modify the files which are not related to the issue.

2017-07-08 17:56 UTC, jarifibrahim commented on oshc/main/templates/session.html
> -<html>
Extraneous change. Please do not modify the files which are not related to the issue.

2017-07-08 17:56 UTC, jarifibrahim commented on oshc/oshc/settings.py
> +DEBUG = os.getenv("DEBUG", True)
Extraneous change. Please do not modify the files which are not related to the issue.

2017-07-09 17:40 UTC, jarifibrahim approved these changes
LGTM

2017-07-09 17:52 UTC, jarifibrahim requested changes

2017-07-09 17:52 UTC, jarifibrahim commented on oshc/main/regbackend.py
> +    return None
Indentation error

2017-07-09 18:04 UTC, jarifibrahim approved these changes

2017-07-11 17:49 UTC, merged