Admin can store session in database
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #79
Opened 2017-07-18 18:03 UTC by vaibhavsingh97

**Status**:
- [x] Ready
- [ ] In Development
- [ ] On Hold

**Which issue does this PR fix?**: 
fixes #73 

Brief description of what this PR does.
This PR will allow admin to add and delete sessions. Also, Latest 3 sessions will be displayed on the homepage.

**Why do we need this PR?**:
Currently, We have to add sessions manually and to do that we have to edit page itself. Now, admin can add the session in one place and changes will be reflected to the homepage.

**Demo (optional)**:
Admin Screens:
![image](https://user-images.githubusercontent.com/8705386/28331932-916aba3e-6c10-11e7-9953-73887f39869c.png)
![image](https://user-images.githubusercontent.com/8705386/28332064-008b333a-6c11-11e7-9309-32a52e11058c.png)
User screen:
![image](https://user-images.githubusercontent.com/8705386/28332104-20619dca-6c11-11e7-8c51-671585d038ef.png)

Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.

**Testing instructions:**:
1. `git checkout develop`
2. `python manage.py makemigrations`
3. `python manage.py migrate`
4. `python manage.py collectstatic`
5. `python manage.py runserver`
6.  To add sessions, goto `http://127.0.0.1:8000/admin/main/chatsession/add/`

2017-07-18 18:07 UTC, vaibhavsingh97 commented
@tapasweni-pathak @nikhita @jarifibrahim Please review

2017-07-19 06:40 UTC, jarifibrahim commented
@tapasweni-pathak Please enable Travis builds for Pull Requests.

2017-07-19 07:18 UTC, jarifibrahim requested changes
@vaibhavsingh97 Could you please add a few tests for this PR?

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/models.py
>  # Create your models here.
Please remove this comment

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/models.py
> +    description = models.CharField(max_length=512, help_text="Require description of the session")
`models.TextField` would be better for description. We'll have `Textarea` widget by default.

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/models.py
> +    title = models.CharField(max_length=128, help_text="Require title of the session")
`help_text="Title of the session"` would be more appropriate. All the fields are mandatory by default. You don't need to add an explicit `require` :)

The same goes for all the fields in the model.

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/models.py
> +class PostModelForm(ModelForm):
Why do we need `PostModelForm`?

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/models.py
> +        fields = ('title', 'profile_name', 'profile_url', 'description', 'start_date', 'end_date', 'register_url')
All the model fields will be displayed on the admin page by default. You don't need to add them explicitly.

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/models.py
> +            'description': Textarea(attrs={'cols': 50, 'rows': 6}),
If we use `TextField` for description, this won't be necessary. `Textarea` is the default widget for `TextField`

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/templates/index.html
> +                                    </button>
Fix indentation.

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/admin.py
>  # Register your models here.
Please remove this comment.

2017-07-19 07:18 UTC, jarifibrahim commented on oshc/main/admin.py
> +    form = PostModelForm
We don't need `PostModelForm`.

2017-07-19 11:41 UTC, vaibhavsingh97 commented
@jarifibrahim Please review again

2017-07-19 13:48 UTC, tapasweni-pathak commented
@jarifibrahim It is already running on the pull requests.

2017-07-22 13:37 UTC, vaibhavsingh97 commented
Closing this PR as lot of issues.

2017-07-22 13:37 UTC, closed without merging