Added coveralls.io badge to README.md
OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io pull request #88
Opened 2017-07-24 09:10 UTC by cmdrwebdev

**Status**:
- [ ] Ready
- [ ] In Development
- [ ] On Hold

**Which issue does this PR fix?**: fixes #

Brief description of what this PR does.
Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber"

**Why do we need this PR?**:

If relevant, please include a screenshot.

**Demo (optional)**:

Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.

**Testing instructions:**:

If there is any work still left to do, please add it here.

**TODOs (if any)**:

**A picture of a cute animal (not mandatory but encouraged)**:

2017-07-24 10:27 UTC, vaibhavsingh97 requested changes

2017-07-24 10:27 UTC, vaibhavsingh97 commented on README.md
> +
Travis CI and coveralls coverage should come in one line

2017-07-24 10:30 UTC, vaibhavsingh97 commented
@cmdrwebdev when you create PR it's should describe what this PR does and which issue this PR fixed so use `fixes #23` where 23 is the issue number. Although, you don't have to remember the issue number just write # and start writing the issue title, GitHub will automatically suggest issues. Please answer 2nd and 3rd question .

2017-07-24 13:33 UTC, cmdrwebdev commented on README.md
> +
Sorry @vaibhavsingh97  that was my first contribution. For the PR do i need to request another PR or just push commit and edit my existing comment to update my answer to question 2 and 3?

2017-07-24 14:34 UTC, vaibhavsingh97 commented on README.md
> +
@cmdrwebdev First of all congratulations!! :tada: :tada: You have made your first PR and it needs minor changes. You have to push commit again in order to reflect new changes.

2017-07-25 05:35 UTC, nikhita approved these changes

2017-07-25 05:37 UTC, merged

2017-07-25 05:38 UTC, nikhita commented
@cmdrwebdev Congratulations on getting your first PR merged!!! :tada: :tada: :tada:

2017-07-25 05:46 UTC, cmdrwebdev commented
Thanks @nikhita